version: "3.9"

services:
  ad:
    build:
      context: ./src/ad
      dockerfile: Dockerfile
    image: akashp490/adservice:v1
    container_name: ad
    ports:
      - "8080:8080"
    restart: unless-stopped

  product-catalog:
    build:
      context: ./src/product-catalog
      dockerfile: Dockerfile
    image: akashp490/product-catalog:v1
    container_name: product-catalog
    ports:
      - "8081:8080"
    restart: unless-stopped

  recommendation:
    build:
      context: ./src/recommendation
      dockerfile: Dockerfile

    image: akashp490/recommendation:v1
    container_name: recommendation
    ports:
      - "8082:8080"
    environment:
      OTEL_SERVICE_NAME: recommendation
      PRODUCT_CATALOG_ADDR: product-catalog:8080

    restart: unless-stopped

    depends_on:
      - product-catalog
